[package]
name = "vanity-key"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.1"
rand = "0.8.5"
rsa = "0.7.1"

